version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: supllyflow
    networks:
      - supllyflow-net

  api:
    image: supllyflow-api:0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npx ts-node src/index.ts
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:123@supllyflow:5432/app?schema=public
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - supllyflow-net
  
networks:
  supllyflow-net:
  